### ISSUE TITLE
Colliding filenames

### ISSUE THREAD

**Issue by line-o** [BetaMasaheft/Persons#582]
A checkout of this repository on a filesystem that is case-insensitive (e.g. on MacOS) leads to following warning:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'PRS2001-3000/PRS2174Assfalg.xml'
  'PRS2001-3000/PRS2174Aßfalg.xml'
  'PRS4001-5000/PRS4841GrosseOe.xml'
  'PRS4001-5000/PRS4841GroßeOe.xml'
```

**Comment by eu-genia** [comment]
I do not know how these doublets emerged but I have now removed them, hope it is OK
(We have internally agreed to have issues only under Documentation so that we do not miss anything)
