### ISSUE TITLE
PRS14464WaldaTansae

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Persons#904]
I found out that there is no file for https://www.betamasaheft.eu/persons/PRS14464WaldaTansae/main, 
and it is not used anywhere; the name is Walda Tanśāʾe, written incorrectly. Perhaps it was created by mistake, 
do we need this? Can it be deleted?

**Comment by DenisNosnitsin1970** [comment]
Ok, no problem.

**Comment by CarstenHoffmannMarburg** [comment]
I updated the records, which have not been approved, yet: https://github.com/BetaMasaheft/Persons/pull/870/files.
